[ITG-68] added filters to Task api
it-goats/it-goats pull request #36
Opened 2022-05-04 18:35 UTC by Gajkes

added filters to Task api

2022-05-04 18:42 UTC, koszar91 approved these changes
Code looks nice. There will be some compatibility isuues with other branches, but probably it won't be your concern XD, you were first to PR.

2022-05-04 22:40 UTC, gregori0o approved these changes

2022-05-05 08:06 UTC, john-sonz requested changes

2022-05-05 08:06 UTC, john-sonz commented on bode/bode/resources/tasks/api.py
> +        return Task.query.filter(*all_filters).all()
Bring back the ordering, please!

2022-05-05 08:06 UTC, john-sonz commented on bode/bode/resources/tasks/api.py
> +            all_filters.append(Task.title.like("%" + title + "%"))
```suggestion
            all_filters.append(Task.title.ilike(f"%{title}%"))
```

2022-05-05 08:06 UTC, john-sonz commented on bode/bode/resources/tasks/api.py
> +                or_filters.append(Task.tags.any(Tag.name == tag))
```suggestion
            or_filters = [Task.tags.any(Tag.name == tag) for tag in tags]
```

2022-05-08 14:25 UTC, john-sonz approved these changes
Looks good!

2022-05-12 17:13 UTC, closed without merging