[ITG-104] Add icon of type to the task.
it-goats/it-goats pull request #42
Opened 2022-05-11 21:36 UTC by gregori0o

2022-05-11 21:43 UTC, bkulawska commented
Something's not working when I try to run the application, idk if it's my fault:
![image](https://user-images.githubusercontent.com/76395559/167952828-f2c15e14-18e6-405d-9519-5ada63faa52c.png)

2022-05-11 23:03 UTC, gregori0o commented
> Something's not working when I try to run the application, idk if it's my fault or what: ![image](https://user-images.githubusercontent.com/76395559/167952828-f2c15e14-18e6-405d-9519-5ada63faa52c.png)

Try re-run `docker-compose up` after you changed branch to this.

2022-05-12 07:31 UTC, koszar91 requested changes
Good job, the icons are beautiful. Let's consider little redesign of the task list item, it;s getting more and more populated with data 😍

2022-05-12 07:31 UTC, koszar91 commented on cabra/src/pages/components/TaskListItem.tsx
> +        )}
Got some remarks about this div.
It is visible conditionally, and I think it's bad. I think we should render it always, maybe with some faded empty containers to show the task is unrelated.
Also not-constant task size is vary bad.
What about this concept (it includes resizing all cards in the task a bit):
![image](https://user-images.githubusercontent.com/72392522/168015175-1f8d6f70-56ea-4e68-b3a7-d7cc3b664b96.png)

2022-05-12 07:31 UTC, koszar91 commented on cabra/src/pages/components/TaskListItem.tsx
> +    >
I think coloring the subtask is not necessary. We have an icon, it's enough information.

2022-05-12 10:44 UTC, john-sonz approved these changes
LGTM!

2022-05-12 10:44 UTC, john-sonz commented on cabra/src/pages/components/TaskTypeIcon.tsx
> +}
You can shorten this bit with some smart object shenanigans:
```suggestion
const TYPES_TO_ICONS = {
  [DirectedRelationType.Subtask]: {
    Icon: DuplicateIcon,
    message: "Subtask",
  },
  [DirectedRelationType.Supertask]: {
    Icon: CollectionIcon,
    message: "Has subtask",
  },
  [DirectedRelationType.Blocks]: {
    Icon: ArrowCircleDownIcon,
    message: "Blocks another task",
  },
  [DirectedRelationType.IsBlockedBy]: {
    Icon: ArrowCircleUpIcon,
    message: "Is blocked by another task",
  },
  [DirectedRelationType.Interchangable]: {
    Icon: SwitchHorizontalIcon,
    message: "Interchangeable task",
  },
};

export function TaskTypeIcon({ type }: Props) {
  const { Icon, message } = TYPES_TO_ICONS[type];

  return (
    <IconContainer>
      <Icon height={20} width={20} data-tip data-for={type} />
      <ReactTooltip id={type} place="bottom" effect="solid">
        {message}
      </ReactTooltip>
    </IconContainer>
  );
}
```

2022-05-12 14:09 UTC, bkulawska approved these changes
Looks nice <3

2022-05-12 14:11 UTC, koszar91 approved these changes
b e a u t i f u l  ❤

2022-05-12 14:26 UTC, merged