[ITG-111] Przystosować backend do nowej mechaniki dodawania i edycji zadań
it-goats/it-goats pull request #54
Opened 2022-06-05 20:58 UTC by bkulawska

[WIP] Only creation of tasks for now, let me know if the code is okay.
I tested maunally in postman and it seems to be working fine.

2022-06-06 07:43 UTC, john-sonz reviewed
The logic looks alright so I think you can proceed to implementing the editing part

2022-06-06 08:54 UTC, koszar91 reviewed
Looks fine, good job, i hope task editing will not be harder than that

2022-06-09 14:52 UTC, john-sonz requested changes
The API shape here doesn't match the one in #55. @bkulawska, @koszar91 please decide on a common format and implement it.

2022-06-13 17:12 UTC, john-sonz commented on bode/bode/models/task/actions.py
> +            create_task_relation(**subtask_relation_input)
This could be extracted, so that it's not repeated in edition and creation

2022-06-13 17:12 UTC, john-sonz commented on bode/bode/resources/tasks/schemas.py
> +    type = fields.String(validate=validate.OneOf(DirectedRelationType.list()), required=True)
You're not handling the subtask relation types so they should be excluded from the possible types here

2022-06-19 15:31 UTC, john-sonz approved these changes

2022-06-19 15:32 UTC, merged